# Generated by Django 5.0.7 on 2024-11-19 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user1_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user2_id',
        ),
        migrations.AddField(
            model_name='friend',
            name='friendname',
            field=models.ForeignKey(help_text='Reference to the receiving user in the friend request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_friendname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='username',
            field=models.ForeignKey(help_text='Reference to the initiating user in the friend request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
