# Generated by Django 5.0.7 on 2024-11-20 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_friend_status_remove_friend_user1_id_and_more'),
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendname',
            field=models.ForeignKey(help_text='Reference to the receiving user in the friend request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_friendname', to='users.user'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='username',
            field=models.ForeignKey(help_text='Reference to the initiating user in the friend request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_username', to='users.user'),
        ),
    ]
