version: "3"

services:
  django:
    build: backend/
    container_name: django
    # ports:
    #   - 8000:8000 # API 문서 확인을 위한 포트포워딩
    expose:
      - "8000" # 개발완료시 해당 주석 해제 후 ports 제거 필요합니다
    volumes:
      - type: bind
        source: ./backend
        target: /app
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    container_name: postgres
    env_file: .env

  nginx:
    build: nginx/
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    restart: always
    depends_on:
      - django
