version: "3"

services:
  django:
    build: django/
    image: django
    container_name: django
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./django
        target: /web
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    container_name: postgres
    env_file: .env

  nginx:
    build: nginx/
    image: nginx
    ports:
      - '1443:443'
    container_name: nginx
    restart: always
    depends_on:
      - django
