# Generated by Django 5.0.7 on 2024-11-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '오프라인'), (1, '온라인')], default=0, help_text='User activity status'),
        ),
    ]
