# Generated by Django 4.2.14 on 2024-08-19 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_result', models.CharField(blank=True, choices=[('user_win', '사용자 승리'), ('opponent_win', '상대방 승리'), ('pending_result', '결과 대기중')], default='pending_result', max_length=40)),
                ('match_start_time', models.DateTimeField(auto_now_add=True)),
                ('match_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user1_grade', models.IntegerField(blank=True, default=0)),
                ('user2_grade', models.IntegerField(blank=True, default=0)),
                ('match_type', models.CharField(choices=[('tournament', '토너먼트 경기'), ('match', '1대1경기')], default='match', max_length=10)),
                ('user1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_user1', to='users.user')),
                ('user2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_user2', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_matches', to='games.match')),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_matches', to='games.match')),
                ('semifinal1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_matches1', to='games.match')),
                ('semifinal2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semifinal_matches2', to='games.match')),
            ],
        ),
    ]
