# Generated by Django 4.2.14 on 2024-08-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
                ('profile_img', models.IntegerField(choices=[(1, '피카츄'), (2, '이상해씨'), (3, '파이리'), (4, '잉어킹')], default=1)),
                ('exp', models.IntegerField(default=0)),
                ('macrotext1', models.CharField(blank=True, default='good game', max_length=20)),
                ('macrotext2', models.CharField(blank=True, default='thanks', max_length=20)),
                ('macrotext3', models.CharField(blank=True, default='bye bye', max_length=20)),
                ('macrotext4', models.CharField(blank=True, default='goooooood!', max_length=20)),
                ('macrotext5', models.CharField(blank=True, default='hello', max_length=20)),
            ],
        ),
    ]
