# Generated by Django 5.0.7 on 2024-08-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login_id', models.CharField(max_length=10)),
                ('user_login_password', models.CharField(max_length=20)),
                ('user_profile_nickname', models.CharField(max_length=10)),
                ('user_macrotext1', models.CharField(blank=True, default='good game', max_length=20, null=True)),
                ('user_macrotext2', models.CharField(blank=True, default='thanks', max_length=20, null=True)),
                ('user_macrotext3', models.CharField(blank=True, default='bye bye', max_length=20, null=True)),
                ('user_macrotext4', models.CharField(blank=True, default='goooooood!', max_length=20, null=True)),
                ('user_macrotext5', models.CharField(blank=True, default='hello', max_length=20, null=True)),
                ('user_image_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.image')),
            ],
        ),
    ]
