# Generated by Django 5.0.7 on 2024-08-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('users', '0002_alter_user_exp_alter_user_macrotext1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', '대기상태'), ('accepted', '친구상태')], default='pending', help_text='Current status of the friend request.', max_length=10),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user1_id',
            field=models.ForeignKey(help_text='Reference to the initiating user in the friend request.', on_delete=django.db.models.deletion.CASCADE, related_name='friends_initiated', to='users.user'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user2_id',
            field=models.ForeignKey(help_text='Reference to the receiving user in the friend request.', on_delete=django.db.models.deletion.CASCADE, related_name='friends_received', to='users.user'),
        ),
    ]
