# Generated by Django 5.0.7 on 2024-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0, help_text='Experience points accumulated by the user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='macrotext1',
            field=models.CharField(blank=True, default='good game', help_text="Macro text 1, default is 'good game'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='macrotext2',
            field=models.CharField(blank=True, default='thanks', help_text="Macro text 2, default is 'thanks'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='macrotext3',
            field=models.CharField(blank=True, default='bye bye', help_text="Macro text 3, default is 'bye bye'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='macrotext4',
            field=models.CharField(blank=True, default='goooooood!', help_text="Macro text 4, default is 'goooooood!'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='macrotext5',
            field=models.CharField(blank=True, default='hello', help_text="Macro text 5, default is 'hello'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='Nickname for the user.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password for the user login.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.IntegerField(choices=[(1, '피카츄'), (2, '이상해씨'), (3, '파이리'), (4, '잉어킹')], default=1, help_text='Profile image ID for the user, selectable from predefined options.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username used as the login ID for the user.', max_length=10),
        ),
    ]
